"""Flavor constants."""

DOC_NAME = "Flavor name in the Resource Provider."
DOC_UUID = "Flavor unique ID in the Resource Provider."
DOC_DISK = "Reserved disk size (GiB)."
DOC_SHARED = "Public or private Flavor."
DOC_RAM = "Reserved RAM (MiB)."
DOC_VCPUS = "Number of Virtual CPUs."
DOC_SWAP = "Swap size (GiB)."
DOC_EPHEM = "Ephemeral disk size (GiB)."
DOC_INFI = "MPI - parallel multi-process enabled."
DOC_GPUS = "Number of GPUs."
DOC_GPU_MOD = "GPU model name."
DOC_GPU_VND = "Name of the GPU vendor."
DOC_LOC_STO = "Local storage presence."

DOC_EXT_PROJ = "Projects having access to this flavor. Filled only for private flavors."
DOC_EXT_SERV = "Compute Service supporting this flavor."
