services:
  db:
    image: neo4j:5.18
    container_name: neo4j-db
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 15
    restart: unless-stopped
