"""Definition of Provider constants."""

DOC_NAME = "Provider name."
DOC_TYPE = "Provider type."
DOC_STAT = "Provider status."
DOC_SHARED = "Public or private Provider."
DOC_EMAIL = "list of maintainers emails."
DOC_EXT_AUTH_METH = "Authentication method used by the Provider."
DOC_EXT_IDP = "Supported identity providers."
DOC_EXT_PROJ = "Supplied projects."
DOC_EXT_REG = "Supplied regions."
DOC_NEW_PROJ_UUID = "Target project's UUID in the Provider."
DOC_NEW_PROJ_UUIDS = (
    "list of projects' UUID in the Provider having access to the resource."
)
DOC_NEW_SLA = "SLA owned by this project and related to this provider."
DOC_NEW_GROUP = "Owned user groups owning the SLAs involving this provider."
DOC_NEW_SERV_BLO_STO = "Supplied block storage services."
DOC_NEW_SERV_COMP = "Supplied compute services."
DOC_NEW_SERV_ID = "Supplied identity services."
DOC_NEW_SERV_NET = "Supplied network services."
