"""Image constants."""

DOC_NAME = "Image name in the Resource Provider."
DOC_UUID = "Image unique ID in the Resource Provider."
DOC_OS_TYPE = "OS type."
DOC_OS_DISTR = "OS distribution."
DOC_OS_VERS = "Distribution version."
DOC_ARCH = "OS architecture."
DOC_KERN = "Kernel version."
DOC_CUDA = "Support for cuda enabled."
DOC_GPU_DRIV = "Support for GPUs drivers enabled."
DOC_SHARED = "Public or private Image."
DOC_TAGS = "list of tags associated to this Image."
DOC_CREATED_AT = "Creation time"

DOC_EXT_PROJ = "Projects having access to this image. Filled only for private images."
DOC_EXT_SERV = "Compute Service owning this image."
