"""Definition of Quotas constants."""

DOC_PER_USER = "This limitation should be applied to each user."
DOC_GB = "Number of max usable gigabytes (GiB)."
DOC_VOL_GB = "Number of max usable gigabytes per volume (GiB)."
DOC_VOLS = "Number of max volumes a user group can create."
DOC_CORES = "Number of max usable cores."
DOC_INST = "Number of max VM instances."
DOC_RAM = "Number of max usable RAM (MiB)."
DOC_PUB_IPS = "The number of floating IP addresses allowed for each project."
DOC_NETS = "The number of networks allowed for each project."
DOC_PORT = "The number of ports allowed for each project."
DOC_GROUPS = "The number of security groups allowed for each project."
DOC_GROUP_RULES = "The number of security group rules allowed for each project."
DOC_EXT_SERV = "Target service. Same type of quota."
DOC_EXT_PROJ = "Target project."
DOC_USAGE = "Flag to determine if this quota represents the current usage."
