"""Definition of Network constants."""

DOC_NAME = "Network name in the Provider."
DOC_UUID = "Network unique ID in the Provider."
DOC_SHARED = "Public or private Network."
DOC_EXT_ROUT = "Network with access to outside networks. External network."
DOC_DEFAULT = "Network to use as default."
DOC_MTU = "Metric transmission unit (B)."
DOC_PROXY_HOST = "Proxy IP address or hostname. Accept port number."
DOC_PROXY_USER = "Proxy username."
DOC_TAGS = "List of tags associated to this Network."
DOC_EXT_PROJ = "Project having access to this network if the network is not shared."
DOC_EXT_SERV = "Network Service supplying this network."
