"""Definition of Services constants."""

DOC_ENDP = "URL of the IaaS Service."
DOC_TYPE = "Service type."
DOC_NAME = "Service name. Depends on type."
DOC_EXT_REG = "Region hosting this service."
DOC_EXT_QUOTA = "Quotas pointing to this service."
DOC_EXT_FLAV = "Supplied flavors."
DOC_EXT_IMAG = "Supplied images."
DOC_EXT_NETW = "Supplied networks."
