"""Definition of Image constants."""

DOC_NAME = "Image name in the Provider."
DOC_UUID = "Image unique ID in the Provider."
DOC_OS_TYPE = "OS type."
DOC_OS_DISTR = "OS distribution."
DOC_OS_VERS = "Distribution version."
DOC_ARCH = "OS architecture."
DOC_KERN = "Kernel version."
DOC_CUDA = "Support for cuda enabled."
DOC_GPU_DRIV = "Support for GPUs drivers."
DOC_SHARED = "Public or private Image."
DOC_TAGS = "list of tags associated to this Image."
DOC_EXT_PROJ = "Projects having access to this image. The list is populated only if \
    the image is a private one."
DOC_EXT_SERV = "Compute Service owning this image."
